SELECT e.F_NAME,e.L_NAME, j.START_DATE 
FROM EMPLOYEES e inner join JOB_HISTORY j on e.EMP_ID=j.EMPL_ID
WHERE DEPT_ID =5;


SELECT e.F_NAME,e.L_NAME, j.START_DATE, s.JOB_TITLE
FROM EMPLOYEES e inner join JOB_HISTORY j on e.EMP_ID=j.EMPL_ID
left join JOBS s on j.JOBS_ID= s.JOB_IDENT
WHERE DEPT_ID =5;


SELECT e.EMP_ID,e.L_NAME,e.DEP_ID,d.DEP_NAME
FROM EMPLOYEES e left join DEPARTMENTS d on e.DEP_ID=d.DEPT_ID_DEP;

SELECT e.EMP_ID,e.L_NAME,e.DEP_ID,e.B_DATE,d.DEP_NAME
FROM EMPLOYEES e left join DEPARTMENTS d on e.DEP_ID=d.DEPT_ID_DEP
WHERE year(e.B_DATE)<1980;

SELECT e.EMP_ID,e.L_NAME,e.DEP_ID,e.B_DATE,d.DEP_NAME
FROM EMPLOYEES e left join DEPARTMENTS d on e.DEP_ID=d.DEPT_ID_DEP
and year(e.B_DATE)<1980;

SELECT e.EMP_ID,e.L_NAME,d.DEP_NAME
FROM EMPLOYEES e full outer join DEPARTMENTS d on e.DEP_ID=d.DEPT_ID_DEP;

SELECT e.EMP_ID,e.L_NAME,d.DEPT_ID_DEP,d.DEP_NAME
FROM EMPLOYEES e full outer join DEPARTMENTS d on e.DEP_ID=d.DEPT_ID_DEP AND SEX='M';